frontend/src/routes/[person]/+page.svelte
#18 
Y축을 활용한 같은 종류를 가진 Bar를 모아서 보여주라는 피드백을 적용하기 위해 기존 타임라인에서 Y축을 사용하는 타임라인으로 기능을 구현했다.
visit concept이 겹치면서 date가 겹치는 경우에는 추후 해결 방안을 기획 후 개발 예정이다.
1. 지금 Y축을 만들면서 사실상 Bar의 색상은 이쁘게 보이는거? 정도인데 빼도 괜찮다고 생각합니다. 그래도 보기 편한 부분이 있어서 그냥 색을 그대로 두는 것도 괜찮아 보이는데 의견 부탁드릴게요.
2. 만약 색상을 그대로 둔다면 지금은 단순히 빨, 주, 노, 초 이렇게 해뒀는데 다른 좋은 색 있으면 의견 부탁드리겠습니다.
=> Feat: 타임라인 Y축 생성

frontend/src/lib/components/Charts/BarChart/BarChartTableView.svelte, frontend/src/lib/components/Charts/BarChart/BarChartWrapper.svelte, frontend/src/lib/components/Charts/DonutChart/donutChartTransformer.js, frontend/src/lib/data/patientAnalysisTest.json, frontend/src/routes/cohort/[cohortID]/[person]/+page.svelte
#44 
환자 개인의 기본 통계를 나타내는 페이지를 구현하였습니다.
`Select Tables`가 statistics에서 사용되는 것이 아닌 table에서 사용되는 것 같은데, statistics에서 나와 주석처리 해두었습니다. 수정 부탁드립니다 :)
=> Feat: 환자 기본 통계 페이지 구현

ai/cohort_langchain.py
=> feat : 아틀라스 기반 코호트 구성이 가능한 논문 내용만 추출하는 코드 추가

backend/.gitignore, backend/api/package-lock.json, backend/api/package.json, backend/api/src/controllers/pingController.ts, backend/api/src/db/clickhouse.sql, backend/api/src/db/postgres.sql, backend/api/src/db/types.ts, backend/api/src/example.ts, backend/api/src/index.ts, backend/api/src/query-builder/base.ts, backend/api/src/query-builder/condition-era.ts, backend/api/src/routes/index.ts, backend/api/src/routes/pingRoutes.ts, backend/api/src/services/pingService.ts, backend/api/src/types/type.ts, backend/api/tsconfig.json
- Express와 TypeScript 기반의 API 서버 초기 설정
- MVC 패턴 기반 디렉토리 구조 설계(controllers, routes, services)
- 데이터 필터링을 위한 타입 정의
>
>
당분간 이 브랜치에서 작업을 계속 하려고 하니, 브랜치 삭제하지 마시고 그냥 냅둬주세요!
=> Feat: 백엔드 API 초기 구조 구현

backend/api/src/query-builder/base.ts, backend/api/src/types/type.ts
conceptset 추가
모든 아이디 형식이 Int64인데, js number는 모든 Int64 범위 표현이 어려워서 bigint 형식을 사용하게 수정했습니다. 특히 type.ts에 아이디 형식이 BigInt가 아닌 경우가 있는지, Number로 해야하는데 BigInt로 잘못 들어간 경우가 있는지 검토 부탁드립니다.
>
>
=> Feat: conceptset 추가 및 bigint 추가

backend/api/src/db/clickhouse.sql, backend/api/src/db/postgres.sql, backend/api/src/db/types.ts, backend/api/src/query-builder/base.ts, backend/api/src/query-builder/condition-era.ts, backend/api/src/query-builder/condition-occurrence.ts, backend/api/src/query-builder/death.ts, backend/api/src/query-builder/demographic.ts, backend/api/src/query-builder/device-exposure.ts, backend/api/src/query-builder/dose-era.ts, backend/api/src/query-builder/drug-era.ts, backend/api/src/query-builder/drug-exposure.ts, backend/api/src/query-builder/measurement.ts, backend/api/src/query-builder/observation-period.ts, backend/api/src/query-builder/observation.ts, backend/api/src/query-builder/procedure-occurrence.ts, backend/api/src/query-builder/specimen.ts, backend/api/src/query-builder/visit-occurrence.ts, backend/api/src/types/type.ts
ID 표시에는 BigInt보다 String이 더 적합해 변경했습니다. string을 데이터베이스에 맞게 적절히 변경하기 위해 sql에 _to_int64 함수를 추가했습니다.
First 조건을 추가했습니다.
>
>
first 조건을 select에 추가하는것이 지금 spread 연산자로 되어있는데, 이걸 더 나은 방법으로 표현할 수 있을지 의견 부탁드립니다.
적은 변경으로 너무 자주 리뷰를 드리는 것 같은데, 타입 관련 수정이 있어서 양해 부탁드립니다 ㅎㅎ.. 다음 리뷰는 많이 바뀌어있을 예정입니다.
=> Feat: 타입 변경 및 first 조건 추가

frontend/src/lib/components/Charts/DonutChart/GroupDonutChartWrapper.svelte, frontend/src/routes/cohort/+page.svelte
#68 
코호트 목록 페이지를 디자인했습니다.
- 전반적인 버튼 및 레이아웃 디자인
- 에러 메세지 처리 및 디자인
- 저자 검색 기능 추가
- 페이지네이션 기능 추가
추가적으로 도넛 그룹 차트의 minwidth를 변경한 것은 코호트 수에 따라 half/full로 다르게 보여주는 기능을 추가함에 따라 수정이 필요해진 내용입니다. 너무 작은 수정이라 이번 PR에 같이 넣어두었습니다.
=> Design: 코호트 목록 디자인

backend/api/src/types/type.ts
=> Chore: add comments

backend/api/src/query-builder/index.ts
>
>
구현이 먼저이므로 우선 코드 퀄리티는 제외하고 리뷰해주세요. 나중에 시간이 남으면 리펙토링 하겠습니다.
코호트 쿼리 빌더 작성을 거의 완료했습니다. 최종 코호트 테이블에 INSERT만 하면 완료됩니다.
=> Feat: cohort query build

ai/get_omop_concept_id.py, ai/pdf_to_cohort.py, ai/pdf_to_text.py, ai/query_test.py
> #74 
> 특정 Keyword로 검색했을 때 검색 결과가 하나도 나오지 않는 문제가 있었습니다. 이럴 경우 검색어를 수정하여 재검색하는 기능을 구현하였습니다.
=> Feat: 코호트 keyword 재검색 기능 구현

frontend/src/routes/cohort/[cohortID]/+layout.svelte
#91 
환자 목록에서 사이드바 반응형이 조정되도록 div 태그를 일부 수정했습니다.
=> Feat: 환자 목록 사이드바 반응형 조절

ai/cohort_langchain.py
> # 61 
> 새로운 규격을 langchain을 통해 규격에 맞도록 답변하게 수정함
=> feat : cohort_json_schema 를 통해 llm이 schema를 토대로 답변 하도록 수정

backend/api/package-lock.json, backend/api/package.json, backend/api/src/index.ts, backend/api/src/validators/cohort-definition.validator.ts, backend/api/src/validators/custom-validators.ts, backend/api/src/validators/index.ts, backend/api/src/validators/query.validator.ts, backend/api/src/validators/validator.ts, backend/api/tsconfig.json
body, query 등을 검증하는 validator 추가
>
>
=> Feat: validator 추가

backend/api/package-lock.json, backend/api/package.json, backend/api/src/db/types.ts, backend/api/src/query-builder/index.ts, backend/api/src/types/type.ts
=> Feat: TODO 모두 구현, 각종 버그 수정

frontend/src/routes/login/+page.svelte
#97 
로그인 페이지를 구현했습니다.
아직 로그인 기능은 구현하지 않았습니다. 추후 API 연결 과정에서 기능 구현 이슈파서 진행하도록 하겠습니다. 그리고 로고작업이 다 끝난다면 그때 따로 추가해서 넣도록 하겠습니다.
=> Feat: 로그인 페이지 구현

backend/api/src/types/type.ts
>
>
병원측에서 요구한 코호트 구성 단순화 입니다. 다양한 파트 및 팀에서 해당 규격을 사용중인데 이 규격을 사용하는 부분 모두 바꿔야 하므로 우선 빠르게 규격만 수정해서 올립니다. 현재 수정된 규격에 맞춰 쿼리빌더 등을 수정하지 않아 오류가 나는 상황인데, 우선 무시하고 해당 규격에 대해서만 리뷰 부탁드립니다.
=> Feat: 코호트구성 단순화

backend/api/src/db/types.ts, backend/api/src/query-builder/base.ts, backend/api/src/query-builder/filters/condition-era.ts, backend/api/src/query-builder/filters/condition-occurrence.ts, backend/api/src/query-builder/filters/death.ts, backend/api/src/query-builder/filters/demographic.ts, backend/api/src/query-builder/filters/device-exposure.ts, backend/api/src/query-builder/filters/dose-era.ts, backend/api/src/query-builder/filters/drug-era.ts, backend/api/src/query-builder/filters/drug-exposure.ts, backend/api/src/query-builder/filters/measurement.ts, backend/api/src/query-builder/filters/observation-period.ts, backend/api/src/query-builder/filters/observation.ts, backend/api/src/query-builder/filters/procedure-occurrence.ts, backend/api/src/query-builder/filters/specimen.ts, backend/api/src/query-builder/filters/visit-occurrence.ts, backend/api/src/query-builder/index.ts, backend/api/src/types/type.ts
>
>
새로운 코호트 규격에 맞게 모든 필터와 쿼리빌더를 수정했습니다. 새로운 코호트 규격에서 date 관련 내용이 모두 빠지면서 demographic 필터를 사용할 수 없게 되었습니다. demographic 필터에서 사용할 수 없는 부분만 제거할지, 아니면 필터 자체를 제거할지에 대해서는 추후에 어느정도 백엔드가 완성되면 고민해보는거로 하겠습니다.
=> Feat: 새로운 코호트 구성에 맞게 쿼리빌더 수정

backend/api/package-lock.json, backend/api/package.json, backend/api/src/db/dialects/clickhouse/ClickhouseAdapter.ts, backend/api/src/db/dialects/clickhouse/ClickhouseConnection.ts, backend/api/src/db/dialects/clickhouse/ClickhouseDialect.ts, backend/api/src/db/dialects/clickhouse/ClickhouseDriver.ts, backend/api/src/db/dialects/clickhouse/ClickhouseIntrospector.ts, backend/api/src/db/dialects/clickhouse/README.md, backend/api/src/db/dialects/clickhouse/index.ts, backend/api/src/db/types.ts
=> Feat: clickhouse dialect 구현

backend/api/src/query-builder/filters/demographic.ts, backend/api/src/query-builder/index.ts, backend/api/src/types/type.ts, backend/api/src/validators/cohort-definition.validator.ts
=> Feat: Demographic 추가

backend/api/src/query-builder/base.ts, backend/api/src/query-builder/filters/condition-era.ts, backend/api/src/query-builder/filters/condition-occurrence.ts, backend/api/src/query-builder/filters/death.ts, backend/api/src/query-builder/filters/device-exposure.ts, backend/api/src/query-builder/filters/dose-era.ts, backend/api/src/query-builder/filters/drug-era.ts, backend/api/src/query-builder/filters/drug-exposure.ts, backend/api/src/query-builder/filters/measurement.ts, backend/api/src/query-builder/filters/observation-period.ts, backend/api/src/query-builder/filters/observation.ts, backend/api/src/query-builder/filters/procedure-occurrence.ts, backend/api/src/query-builder/filters/specimen.ts, backend/api/src/query-builder/filters/visit-occurrence.ts, backend/api/src/routes/cohort.route.ts
conditional join을 사용해 쿼리 실행 시간을 단축시켰습니다.
오타를 수정했습니다.
>
>
=> Feat: 쿼리빌더 join 최적화 및 오타 수정

frontend/src/routes/cohort/[cohortID]/+page.svelte
#100 
코호트 Feature탭을 구성했습니다.
UI 중점으로 봐주시면 감사하겠습니다!
=> Feat: 코호트 Feature 탭 뷰 구현

backend/api/package-lock.json, backend/api/package.json, backend/api/src/db/dialects/clickhouse/ClickhouseConnection.ts, backend/api/src/services/cohort.service.ts
kysely clickhouse dialect에서 insert, update시 발생하는 오류를 수정했습니다
>
>
=> Fix: 백엔드 각종 오류 수정

backend/api/package-lock.json, backend/api/package.json, backend/api/src/controllers/cohort.controller.ts, backend/api/src/controllers/ping.controller.ts, backend/api/src/dtos/common.dto.ts, backend/api/src/index.ts, backend/api/src/routes/cohort.route.ts, backend/api/src/routes/ping.route.ts, backend/api/src/services/cohort.service.ts, backend/api/src/services/ping.service.ts
API에서 대량의 데이터가 전송됩니다. 따라서 네트워크 부하를 줄이기 위해 압축을 적용합니다.
>
>
=> Feat: compression 적용

backend/api/src/db/clickhouse.sql, backend/api/src/db/types.ts, backend/api/src/query-builder/filters/condition-era.ts, backend/api/src/query-builder/filters/condition-occurrence.ts, backend/api/src/query-builder/filters/device-exposure.ts, backend/api/src/query-builder/filters/dose-era.ts, backend/api/src/query-builder/filters/drug-era.ts, backend/api/src/query-builder/filters/drug-exposure.ts, backend/api/src/query-builder/filters/measurement.ts, backend/api/src/query-builder/filters/observation-period.ts, backend/api/src/query-builder/filters/observation.ts, backend/api/src/query-builder/filters/procedure-occurrence.ts, backend/api/src/query-builder/filters/specimen.ts, backend/api/src/query-builder/filters/visit-occurrence.ts, backend/api/src/query-builder/index.ts
속도 최적화를 수행했습니다. 특히 작업속도에 병목이 나는 first 관련해서 미리 계산해둡니다.
성능 측면에서는 measurement table 기준 약 1.66배 향상되었으며, 이제 ATLAS 기준 400배 이상 차이납니다.
>
>
=> Feat: 속도 최적화

frontend/src/routes/new/+page.svelte, frontend/src/routes/new/components/CohortAIModal.svelte, frontend/src/routes/new/models/ConceptSet.js, frontend/types.ts
> #103 
> 변경된 코호트 규격에 맞게 코드를 수정하였습니다.
=> Feat: cohort upgrade

backend/api/package-lock.json, backend/api/package.json, backend/api/src/db/clickhouse/ClickhouseAdapter.ts, backend/api/src/db/clickhouse/ClickhouseConnection.ts, backend/api/src/db/clickhouse/ClickhouseDialect.ts, backend/api/src/db/clickhouse/ClickhouseDriver.ts, backend/api/src/db/clickhouse/ClickhouseIntrospector.ts, backend/api/src/db/clickhouse/index.ts, backend/api/src/db/types.ts, backend/api/src/query-builder/base.ts, backend/api/src/query-builder/index.ts
date operator에서 오류가 발생해 수정했습니다
>
>
=> Fix: 각종 버그 수정

backend/api/src/db/clickhouse.sql, backend/api/src/query-builder/index.ts
conceptset 연산 과정의 비효율성을 해결해서 컨셉세트 연산 부분의 속도가 개선되었습니다. (특정 코호트 생성 시간이 3100-3200ms에서 1500-1600ms로 단축됨, 이번에 수정된 부분인 컨셉세트 연산 부분만 보면 약 3배 속도가 개선됨) 추가로, 데이터베이스 테이블 구조도 추가했습니다.
>
>
=> Feat: conceptset 최적화

backend/api/src/cohort/cohort.service.ts, backend/api/src/cohort/dto/cohort.dto.ts, backend/api/src/db/clickhouse.sql
통계를 구현하고, AI쪽에서 필요한 데이터베이스 테이블을 생성했습니다.
>
>
=> Feat: 통계 구현 및 데이터베이스 테이블 생성

backend/api/src/app.module.ts, backend/api/src/person/dto/person.dto.ts, backend/api/src/person/person.controller.spec.ts, backend/api/src/person/person.controller.ts, backend/api/src/person/person.module.ts, backend/api/src/person/person.service.spec.ts, backend/api/src/person/person.service.ts
=> Feat: person api 작성

backend/api/src/app.module.ts, backend/api/src/db/clickhouse.sql, backend/api/src/person/dto/person.dto.ts, backend/api/src/visit/dto/visit.dto.ts, backend/api/src/visit/visit.controller.spec.ts, backend/api/src/visit/visit.controller.ts, backend/api/src/visit/visit.module.ts, backend/api/src/visit/visit.service.spec.ts, backend/api/src/visit/visit.service.ts
=> Feat: visit api 추가

backend/api/src/app.module.ts, backend/api/src/concept/concept.controller.spec.ts, backend/api/src/concept/concept.controller.ts, backend/api/src/concept/concept.module.ts, backend/api/src/concept/concept.service.spec.ts, backend/api/src/concept/concept.service.ts, backend/api/src/concept/dto/concept.dto.ts
=> Feat: concept 검색 api

backend/api/src/cohort/cohort.controller.ts, backend/api/src/cohort/cohort.service.ts, backend/api/src/cohort/dto/cohort.dto.ts, backend/api/src/concept/concept.controller.ts, backend/api/src/concept/concept.service.ts, backend/api/src/concept/dto/concept.dto.ts
=> Feat: pagination에 limit을 직접 적용

backend/api/src/statistics/dto/statistics.dto.ts, backend/api/src/statistics/statistics.service.ts
=> Feat: group에 이름 추가

frontend/src/routes/new/+page.svelte, frontend/src/routes/new/@components/events/operators/DateOperator.svelte, frontend/src/routes/new/@components/events/operators/NumberOperator.svelte, frontend/src/routes/new/components/operators/DateOperator.svelte, frontend/src/routes/new/components/operators/IdentifierOperator.svelte, frontend/src/routes/new/components/operators/NumberOperator.svelte, frontend/src/routes/new/components/operators/StringOperator.svelte
> #156 
> 오퍼레이터의 내용을 영어로 변경하였습니다.
=> feat : change Korean to English

backend/api/src/cohort/dto/cohort.dto.ts, backend/api/src/concept/dto/concept.dto.ts, backend/api/src/db/clickhouse.sql, backend/api/src/db/types.ts, backend/api/src/person/dto/person.dto.ts, backend/api/src/statistics/dto/statistics.dto.ts, backend/api/src/statistics/statistics.controller.ts, backend/api/src/statistics/statistics.service.ts
statistics에 그룹을 생성했습니다. 하나의 statistics에 여러개의 chart를 그릴 수 있도록 했습니다.
>
>
=> Feat: statistics 그룹 생성

frontend/src/routes/cohort/[cohortID]/+page.svelte
#155 
json 규격이 완성되어 feature extractor 코드를 그에 맞게 수정하였습니다.
=> Feat: 규격에 따른 feature extractor 수정

backend/api/src/cohort/cohort.controller.ts, backend/api/src/cohort/cohort.service.ts, backend/api/src/cohort/dto/cohort.dto.ts, backend/api/src/db/clickhouse/ClickhouseConnection.ts
cohort detail을 불러올 때 person count도 불러오게 수정했습니다
>
>
=> Feat: 코호트 detail에 person count 추가

frontend/src/routes/cohort/[cohortID]/+page.svelte
#162 
행 제목을 변경하고, 테스트 데이터를 일부 수정하였습니다.
=> Design: 행 제목 변경

frontend/src/lib/components/ChartCard.svelte, frontend/src/lib/components/Charts/BoxPlot/BoxPlot.svelte, frontend/src/lib/components/Charts/GroupedBarChart/GroupedBarChart.svelte, frontend/src/routes/custom-chart/[chartID]/+page.svelte
#148 
- BoxPlot 컴포넌트 구현
- 커스텀 차트 규격에 맞게 기존 코드(커스텀차트 페이지, GroupedBarChart, BoxPlot) 수정
- Custom Chart Definition 추가
=> Feat: BoxPlot 컴포넌트 구현 및 규격 변경에 따른 수정

backend/api/src/db/clickhouse.sql, backend/api/src/db/types.ts, backend/api/src/feature/dto/feature.dto.ts
=> fix: 변경된 규격 적용

ai/feature-extraction/db.py, ai/feature-extraction/main.py, ai/feature-extraction/model.py
=> f1 score 추가

frontend/src/routes/custom-chart/[chartID]/chart/+page.svelte
> concept sets 통합 및 생성 완료후 페이지 이동
=> feat : concept sets 통합 및 생성 완료후 페이지 이동

backend/api/src/concept/concept.controller.ts, backend/api/src/concept/concept.service.ts, backend/api/src/concept/dto/concept.dto.ts
add domain search on concept
>
>
=> Feat: add domain search on concept

frontend/src/routes/+layout.svelte, frontend/src/routes/guide/+page.svelte
#174 
벤토의 사용자 메뉴얼을 보여주는 가이드 페이지를 만들었습니다.
모든 뷰가 완성되면 이미지를 추가하고, 문구를 수정해 완성시키도록 하겠습니다. 
=> Feat: Guide 페이지 추가

frontend/src/routes/edit/[cohortId]/+page.svelte, frontend/src/routes/edit/[cohortId]/components/CohortAIModal.svelte, frontend/src/routes/new/+server.js
=> Feat cohort ai api bind

frontend/src/routes/cohort/[cohortID]/+page.svelte
#189 
- Comparison Size 아래에 추가
- 줄임처리(호버시 전체 텍스트)
전달 받은 규격과 API 상의 규격이 달라 추후 API 연결 시 프론트 코드 수정이나 백엔드 수정요청이 필요할 것 같습니다.
=> Feat: feature extractor 개선

frontend/src/lib/components/Charts/DonutChart/DonutChart.svelte, frontend/src/lib/components/Table/BioSignal.svelte, frontend/src/lib/components/Table/CDMInfo.svelte, frontend/src/lib/components/Table/Condition.svelte, frontend/src/lib/components/Table/Drug.svelte, frontend/src/lib/components/Table/Observation.svelte, frontend/src/lib/components/Table/ProcedureOccurrence.svelte, frontend/src/lib/components/Table/Specimen.svelte
#190 
Chart Card 예외 처리
CDM 뷰어에서 미믹에 없는 데이터 안뜨게 처리
=> Refactor: 전체 화면 리펙터링

frontend/src/routes/edit/[cohortId]/+page.svelte, frontend/src/routes/edit/[cohortId]/components/CohortAIModal.svelte, frontend/src/routes/edit/[cohortId]/components/ContainerHeader.svelte
> 환자 수가 자동으로 업데이트 되게 변경하였고 코호트 AI의 언어를 영어로 변경하였습니다.
=> Refactor edit cohort 

ai/auto-cohort/get_omop_concept_id.py, ai/auto-cohort/main_without_age_and_date.py
#152 
> api를 "google/gemini-2.5-flash-preview"로 수정 후 속도가 훨씬 빨라짐을 확인하였습니다. 이에 따라 프롬프팅을 수정하였습니다.
=> Feat: 프롬프트 최적화

frontend/src/routes/cohort/[cohortID]/+page.svelte
> edit, delete, copy function 구현
=> feat : edit, delete, copy function 구현

frontend/src/lib/components/ChartCard.svelte, frontend/src/lib/components/Charts/BarChart/BarChart.svelte, frontend/src/lib/components/Charts/BoxPlot/BoxPlot.svelte, frontend/src/lib/components/Charts/DonutChart/DonutChart.svelte, frontend/src/lib/components/Charts/DonutChart/GroupDonutChartWrapper.svelte, frontend/src/lib/components/Charts/DonutChart/Legend.svelte, frontend/src/lib/components/Charts/GroupedBarChart/GroupedBarChart.svelte, frontend/src/routes/cohort/comparison/+page.svelte, frontend/src/routes/custom-chart/[statisticsId]/+page.svelte
#198 
→ test 못함 !!! 테스트 필요
단일 환자 타겟일 때 box plot 처리는 아직 테스트를 진행하지 못한 상태입니다.
=> Fix: 250513 Test 버그 해결

compose.override.yaml, docker-compose.yaml, frontend/.dockerignore, frontend/Dockerfile, frontend/docker-compose.yaml, frontend/docker-start.sh, frontend/package-lock.json, frontend/package.json, frontend/svelte.config.js
프론트 dockerize & docker compose up -d 하나로 모든 부분 다 실행할 수 있도록 수정했습니다
>
>
=> Frontend docker

frontend/src/routes/api/feature/[cohortid]/+server.js, frontend/src/routes/cohort/[cohortID]/+page.svelte
#203 
feature extractor api를 연결했습니다.
=> Feat: feature extractor api 연결 

ai/feature-extraction/main.py
epoch 횟수 단축
> epoch 횟수 100 => 50 단축. 결과가 비슷하여 괜찮을 거 같습니다.
>
>
=> epoch 횟수 줄임

frontend/src/routes/edit/[cohortId]/+page.svelte
> 코호트 구성에서 삭제된 필터 옵션 제거하는 기능을 추가하였습니다.
=> refactor : 삭제된 필터 옵션 제거

frontend/src/routes/edit/[cohortId]/+page.svelte
=> refactor  : 환자수 0 명으로 표시되게 변경

frontend/src/routes/edit/[cohortId]/+page.svelte
> 비교 그룹에서도 숫자가 0으로 표시되게 끔 변경하였습니다.
=> refactor : 비교 그룹에서도 숫자가 0으로 표시되게 끔 변경하였습니다.

frontend/src/routes/cohort/[cohortID]/+page.svelte
> 생성 시에 cohort_id가 아닌 cohortId로 가져오게 변경하였습니다.
=> refactor : cohort_id to cohortID

frontend/src/lib/components/operators/ConceptSelector.svelte, frontend/src/lib/components/operators/DateOperator.svelte, frontend/src/lib/components/operators/IdentifierOperator.svelte, frontend/src/lib/components/operators/NumberOperator.svelte, frontend/src/lib/components/operators/StringOperator.svelte
> 코호트 구성이나 차트 생성 페이지에서 기본 operator 제공 안하게 변경
=> fix : 기본 operator 제공 안하게 변경

frontend/src/routes/cohort/[cohortID]/+page.svelte
=> Fix: 병합 과정 발생한 충돌 해결

frontend/src/routes/cohort/[cohortID]/+page.svelte, frontend/src/routes/custom-chart/+page.svelte, frontend/src/routes/custom-chart/[statisticsId]/+page.svelte, frontend/src/routes/custom-chart/[statisticsId]/components/TargetSetModal.svelte
- 타겟 설정 시 target name, description 입력
- 커스텀 차트 목록에서 커스텀 차트 페이지 삭제 기능 구현
- 하나의 커스텀 차트 페이지에서 해당 페이지 삭제 기능 구현
- 하나의 커스텀 차트 페이지에서 해당 타겟 안의 차트 별 삭제 기능 연결
- 단일 코호트 페이지 내 삭제 아이콘 변경 및 alert 추가
=> Feat: 커스텀 차트 개선

frontend/src/routes/+page.svelte
=> Feat: 홈화면 연결 url 수정 및 info 추가

frontend/src/routes/cohort/[cohortID]/+page.svelte
- Patient Count를 명시적으로 표시
- 단일 코호트 페이지 Definition 복사 기능 추가
=> Feat: 부가 기능 추가

backend/api/src/concept/concept.controller.ts, backend/api/src/concept/concept.service.ts, backend/api/src/feature/dto/feature.dto.ts, backend/api/src/feature/feature.service.ts, backend/api/src/person/person.service.ts, backend/api/src/query-builder/base.ts, backend/api/src/query-builder/cohort.ts, backend/api/src/query-builder/filters/measurement.ts, backend/api/src/query-builder/statistics.ts, backend/api/src/visit/visit.service.ts
=> Optimize int64

ai/feature-extraction/main.py, ai/feature-extraction/model.py
=> Ai memory ptimization

backend/api/src/cohort/cohort.service.ts, backend/api/src/db/clickhouse/ClickhouseConnection.ts, backend/api/src/statistics/statistics.service.ts
=> Optimize clickhouse dialect

ai/auto-cohort/get_omop_concept_id.py, ai/auto-cohort/main_without_age_and_date.py
#236 
> SQL 검색 쿼리 수정하였습니다. concept테이블에서 가져온 개념이 해당 도메인 테이블에도 있는 지 확인하는 부분의 수정이 있었습니다.
=> Fix: Drug 검색 수정

backend/api/src/cohort/cohort.controller.ts, backend/api/src/cohort/cohort.service.ts, backend/api/src/statistics/statistics.controller.ts, backend/api/src/statistics/statistics.service.ts
=> Feat: cohort search

backend/api/src/cohort/cohort.controller.ts, backend/api/src/cohort/dto/cohort.dto.ts, backend/api/src/statistics/dto/statistics.dto.ts, backend/api/src/statistics/statistics.controller.ts
DTO에서 타입이 변하지 않는 오류가 있어 수정했습니다
>
>
=> Fix: type error

frontend/src/routes/cohort/+page.svelte, frontend/src/routes/custom-chart/+page.svelte
#232 
Cohort List, Custom Chart List 페이지에 설명이 부족해 조금 더 자세한 설명으로 추가함.
=> Refactor: 소개 문구 변경
